SPEC := docs/api/openapi.yaml
BACKEND := cd backend &&
FRONTEND := cd frontend &&

.PHONY: codegen data themes back front test eval up

codegen:
	$(BACKEND) uv run datamodel-codegen --input ../$(SPEC) --input-file-type openapi \
		--output app/api_models.py --output-model-type pydantic_v2.BaseModel \
		--target-python-version 3.12 --use-standard-collections --use-union-operator \
		--field-constraints --enum-field-as-literal all --disable-timestamp --formatters ruff-format \
		--custom-file-header "# Generated by datamodel-code-generator from $(SPEC). Do not edit; run make codegen."
	$(FRONTEND) npx --yes openapi-typescript@7.13.0 ../$(SPEC) -o src/api/schema.d.ts

data:
	$(BACKEND) uv run python -m pipeline.build_db && uv run python -m pipeline.build_embeddings

themes:
	$(BACKEND) uv run python -m pipeline.build_themes

back:
	$(BACKEND) uv run uvicorn app.main:app --reload --port 8000

front:
	$(FRONTEND) npm run dev

test:
	$(BACKEND) uv run ruff check . && uv run ruff format --check . && uv run pytest
	$(FRONTEND) npx tsc -b && npm run lint && npx vitest run

eval:
	$(BACKEND) uv run python -m eval.run_eval

up:
	docker compose up --build
