SPEC := docs/api/openapi.yaml
BACKEND := cd backend &&
FRONTEND := cd frontend &&

# Port 5000 is taken by the AirPlay receiver on recent macOS, so the API uses 5001.
API_PORT ?= 5001
WEB_PORT ?= 5173
export API_PORT WEB_PORT

.PHONY: setup dev codegen data themes back front test eval up

setup:
	$(BACKEND) uv sync
	$(FRONTEND) npm ci
	$(MAKE) data

dev:
	@echo "API on http://localhost:$(API_PORT), app on http://localhost:$(WEB_PORT)"
	@trap 'kill 0' EXIT; $(MAKE) back & $(MAKE) front

codegen:
	$(BACKEND) uv run datamodel-codegen --input ../$(SPEC) --input-file-type openapi \
		--output app/api_models.py --output-model-type pydantic_v2.BaseModel \
		--target-python-version 3.12 --use-standard-collections --use-union-operator \
		--field-constraints --enum-field-as-literal all --disable-timestamp --formatters ruff-format \
		--custom-file-header "# Generated by datamodel-code-generator from $(SPEC). Do not edit; run make codegen."
	$(FRONTEND) npx --yes openapi-typescript@7.13.0 ../$(SPEC) -o src/api/schema.d.ts

data:
	$(BACKEND) uv run python -m pipeline.build_db && uv run python -m pipeline.build_embeddings

themes:
	$(BACKEND) uv run python -m pipeline.build_themes

back:
	$(BACKEND) uv run uvicorn app.main:app --reload --port $(API_PORT)

front:
	$(FRONTEND) npm run dev

test:
	$(BACKEND) uv run ruff check . && uv run ruff format --check . && uv run pytest
	$(FRONTEND) npx tsc -b && npm run lint && npx vitest run

eval:
	$(BACKEND) uv run python -m eval.run_eval

up:
	docker compose up --build
