# Generated by datamodel-code-generator from docs/api/openapi.yaml. Do not edit; run make codegen.

from __future__ import annotations

from typing import Literal
from pydantic import BaseModel, ConfigDict, Field, RootModel


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Literal[
        "not_found", "validation_error", "method_not_allowed", "rate_limited", "internal_error"
    ]
    message: str


class Month(RootModel[str]):
    root: str = Field(..., examples=["2025-03"], pattern="^(19|20)\\d{2}-(0[1-9]|1[0-2])$")


class MonthRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: Month
    end: Month


class LlmStatus(
    RootModel[
        Literal["ok", "skipped", "disabled", "failed", "insufficient_evidence", "rate_limited"]
    ]
):
    root: Literal["ok", "skipped", "disabled", "failed", "insufficient_evidence", "rate_limited"]


class Health(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Literal["ok"]
    api_version: str
    llm_enabled: bool


class ThemeOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    theme_id: str
    name: str


class VocabularyPair(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    countries: list[str]
    platforms: list[str]


class YearRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min: int
    max: int


class FilterOptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    genres: list[str] = Field(..., description="Every genre in dataset A")
    primary_genres: list[str]
    year_range: YearRange
    availability: VocabularyPair
    consumption: VocabularyPair
    consumption_months: MonthRange
    distributors: list[str]
    themes: list[ThemeOption]


class MovieSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title_id: str
    title: str
    year: int
    runtime_minutes: int | None
    primary_genre: str | None
    genres: list[str]
    rating: float | None
    vote_count: int | None
    image_url: str | None


class MovieDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title_id: str
    title: str
    year: int
    runtime_minutes: int | None
    primary_genre: str | None
    genres: list[str]
    rating: float | None
    vote_count: int | None
    image_url: str | None
    plot_summary: str | None
    directors: list[str]
    principal_cast: list[str]
    cast: list[str]
    title_url: str | None
    theme: ThemeOption | None


class MovieList(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    results: list[MovieSummary]


class ScoredMovie(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    movie: MovieSummary
    score: float = Field(..., description="Cosine similarity rounded to 4 decimals")


class ScoredMovieList(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    results: list[ScoredMovie]


class SearchFilters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    genres: list[str]
    year_min: int | None
    year_max: int | None
    countries: list[str]
    platforms: list[str]
    people: list[str]


class Interpretation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: LlmStatus
    semantic_query: str | None
    proposed_filters: SearchFilters | None


class SearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    query: str
    semantic_query: str = Field(..., description="The text that was embedded")
    interpretation: Interpretation
    applied_filters: SearchFilters
    results: list[ScoredMovie]


class PlatformOffer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: str
    platform_type: Literal["SVOD", "AVOD"]
    original_flag: str | None
    is_original: bool
    countries: list[str]


class Availability(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title_id: str
    snapshot_month: Month | None
    countries: list[str]
    offers: list[PlatformOffer]


class MetricTotals(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    streams: int = Field(..., ge=0)
    viewing_hours: float = Field(..., ge=0.0)


class MonthlyPoint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    month: Month
    streams: int = Field(..., ge=0)
    viewing_hours: float = Field(..., ge=0.0)


class ShareItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: str
    streams: int = Field(..., ge=0)
    viewing_hours: float = Field(..., ge=0.0)
    share_of_streams: float = Field(..., ge=0.0, le=1.0)


class ConsumptionFilters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    countries: list[str]
    platforms: list[str]


class Performance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title_id: str
    applied_filters: ConsumptionFilters
    options: ConsumptionFilters
    period: MonthRange | None
    totals: MetricTotals
    series: list[MonthlyPoint]
    by_country: list[ShareItem]
    by_platform: list[ShareItem]


class Narrative(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: LlmStatus
    text: str | None


class InsightFacts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total_streams: int
    viewing_hours: float
    months_with_data: int
    first_month: Month | None
    last_month: Month | None
    peak_month: Month | None
    peak_streams: int | None
    top_country: str | None
    top_country_share: float | None
    top_platform: str | None
    top_platform_share: float | None
    engagement: float | None


class Insight(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title_id: str
    facts: InsightFacts
    narrative: Narrative


class DashboardFilters(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: Month
    end: Month
    countries: list[str]
    platforms: list[str]
    genres: list[str]
    themes: list[str]
    distributors: list[str]


class Kpi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: float | None
    previous: float | None
    change_pct: float | None = Field(..., description="Relative change, for counts")
    change_pp: float | None = Field(..., description="Change in percentage points, for ratios")


class DashboardSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filters: DashboardFilters
    previous_period: MonthRange | None
    streams: Kpi
    viewing_hours: Kpi
    titles_with_consumption: Kpi
    engagement: Kpi


class TrendGroup(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: str
    series: list[MonthlyPoint]


class BreakdownDimension(
    RootModel[Literal["platform", "country", "primary_genre", "theme", "release_year"]]
):
    root: Literal["platform", "country", "primary_genre", "theme", "release_year"]


class BreakdownItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: str
    label: str
    streams: int = Field(..., ge=0)
    viewing_hours: float = Field(..., ge=0.0)
    titles: int = Field(..., ge=0)
    streams_per_title: float | None
    share_of_streams: float = Field(..., ge=0.0, le=1.0)


class DashboardBreakdown(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filters: DashboardFilters
    dimension: BreakdownDimension
    items: list[BreakdownItem]


class MatrixCell(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: str
    country: str
    streams: int = Field(..., ge=0)
    titles: int = Field(..., ge=0)
    streams_per_title: float | None


class DashboardMatrix(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filters: DashboardFilters
    platforms: list[str]
    countries: list[str]
    cells: list[MatrixCell]


class TitleSort(RootModel[Literal["streams", "viewing_hours", "engagement", "growth"]]):
    root: Literal["streams", "viewing_hours", "engagement", "growth"] = "streams"


class RankedTitle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rank: int = Field(..., ge=1)
    movie: MovieSummary
    streams: int = Field(..., ge=0)
    viewing_hours: float = Field(..., ge=0.0)
    engagement: float | None
    growth_pct: float | None


class DashboardTitles(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filters: DashboardFilters
    sort: TitleSort
    total: int = Field(..., ge=0)
    offset: int = Field(..., ge=0)
    limit: int = Field(..., ge=1)
    items: list[RankedTitle]


class Mover(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    movie: MovieSummary
    streams: int = Field(..., ge=0)
    previous_streams: int = Field(..., ge=0)
    change: int


class ShareShift(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dimension: Literal["platform", "country"]
    key: str
    share: float
    previous_share: float
    change_pp: float


class DashboardChanges(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filters: DashboardFilters
    previous_period: MonthRange | None
    gainers: list[Mover] = Field(..., max_length=5)
    decliners: list[Mover] = Field(..., max_length=5)
    share_shifts: list[ShareShift]
    narrative: Narrative


class CollectionSection(RootModel[Literal["country", "now", "platform", "theme"]]):
    root: Literal["country", "now", "platform", "theme"]


class CollectionSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    collection_id: str
    title: str
    description: str
    section: CollectionSection
    metric_label: str
    preview: list[MovieSummary] = Field(..., max_length=4)


class CollectionList(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    collections: list[CollectionSummary]


class CollectionItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rank: int = Field(..., ge=1)
    movie: MovieSummary
    metric_value: float | None


class Collection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    collection_id: str
    title: str
    description: str
    section: CollectionSection
    metric_label: str
    items: list[CollectionItem] = Field(..., max_length=30)


class DemandSignal(RootModel[Literal["strong", "moderate", "weak", "insufficient_evidence"]]):
    root: Literal["strong", "moderate", "weak", "insufficient_evidence"]


class Comparable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    movie: MovieSummary
    similarity: float
    first_six_month_streams: int | None = Field(
        ..., description="Null when the movie never streamed on the target platform and country"
    )
    eligible: bool = Field(..., description="True when the full 6-month window is observed")


class ExpectedRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Literal["ok", "insufficient_evidence"]
    p25: float | None
    median: float | None
    p75: float | None
    benchmark: float | None
    eligible_count: int = Field(..., ge=0)


class PlatformFitItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: str
    titles: int = Field(..., ge=0)
    streams_per_title: float | None


class WhitespaceItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    country: str
    comparables_with_streams: int = Field(..., ge=0)


class LicensingTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: str
    country: str


class LicensingAssessment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    movie: MovieSummary
    target: LicensingTarget
    already_on_target: bool
    title_totals: MetricTotals
    availability_countries: list[str]
    comparables: list[Comparable] = Field(..., max_length=20)
    expected_range: ExpectedRange
    signal: DemandSignal
    platform_fit: list[PlatformFitItem]
    whitespace: list[WhitespaceItem]


class LicensingMemo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: LlmStatus
    signal: DemandSignal
    headline: str | None
    evidence: list[str]
    risks: list[str]
    caveats: list[str]


class Logline(RootModel[str]):
    root: str = Field(..., max_length=600, min_length=20)


class ConceptsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    loglines: list[Logline] = Field(..., max_length=3, min_length=1)


class ConceptResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: int = Field(..., description="Position in the request", ge=0)
    logline: str
    rank: int = Field(..., ge=1)
    demand_index: float | None
    eligible_count: int = Field(..., ge=0)
    saturation: int = Field(..., ge=0)
    comparables: list[ScoredMovie] = Field(..., max_length=20)
    demand_by_country: list[ShareItem]


class ConceptsEvaluation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    concepts: list[ConceptResult]


class ConceptsMemo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: LlmStatus
    summary: str | None
    per_concept: list[str]
    caveats: list[str]


class ChatMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Literal["user", "assistant"]
    content: str = Field(..., max_length=1000, min_length=1)


class AssistantRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messages: list[ChatMessage] = Field(..., max_length=12, min_length=1)


class AssistantStatus(
    RootModel[
        Literal[
            "answered",
            "no_data",
            "out_of_scope",
            "conversation",
            "disabled",
            "failed",
            "rate_limited",
        ]
    ]
):
    root: Literal[
        "answered", "no_data", "out_of_scope", "conversation", "disabled", "failed", "rate_limited"
    ] = Field(
        ...,
        description="conversation (added in 1.4.0): greetings, thanks and clarifying questions; no figures allowed. rate_limited (added in 1.5.0): a usage limit on model calls was reached.",
    )


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tool: Literal["run_sql", "search_movies"]
    purpose: str
    sql: str | None
    columns: list[str]
    rows: list[list[str | float | bool | None]] = Field(..., max_length=200)
    row_count: int = Field(..., ge=0)
    error: str | None


class AssistantReply(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: AssistantStatus
    answer: str | None
    evidence: list[Evidence]


class Person(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    roles: list[Literal["director", "cast"]]
    movie_count: int = Field(..., ge=1)


class PersonList(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    results: list[Person]


class MarketOpportunity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    platform: str
    country: str
    signal: DemandSignal
    median: float | None
    benchmark: float | None
    ratio: float | None
    eligible_count: int = Field(..., ge=0)
    already_available: bool


class MarketOpportunities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    movie: MovieSummary
    comparable_count: int = Field(..., ge=0)
    targets: list[MarketOpportunity]


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: ErrorBody


class DashboardTrend(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filters: DashboardFilters
    series: list[MonthlyPoint]
    groups: list[TrendGroup]
