import {
  Eye,
  Film,
  Fingerprint,
  Ghost,
  Heart,
  KeyRound,
  Landmark,
  Laugh,
  Mic,
  Mountain,
  Music,
  Music2,
  Palette,
  Rocket,
  Swords,
  Tent,
  Theater,
  Trophy,
  Tv,
  UserRound,
  Users,
  Video,
  WandSparkles,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const GENRE_ICONS: Record<string, LucideIcon> = {
  Action: Zap,
  Adventure: Mountain,
  Animation: Palette,
  Biography: UserRound,
  Comedy: Laugh,
  Crime: Fingerprint,
  Documentary: Video,
  Drama: Theater,
  Family: Users,
  Fantasy: WandSparkles,
  History: Landmark,
  Horror: Ghost,
  Music: Music,
  Musical: Music2,
  Mystery: KeyRound,
  'Reality-TV': Tv,
  Romance: Heart,
  'Sci-Fi': Rocket,
  Sport: Trophy,
  'Talk-Show': Mic,
  Thriller: Eye,
  War: Swords,
  Western: Tent,
}

export function genreIcon(genre: string): LucideIcon {
  return GENRE_ICONS[genre] ?? Film
}
